-- ============================================================
-- MODULO INVENTARIO  Coleg.IO
-- Ejecutar completo en SQL editor de Supabase
-- ============================================================

create table if not exists inventario_items (
  id              bigint generated always as identity primary key,
  tipo            text    not null,
  categoria       text,
  producto        text    not null,
  talla           text,
  area            text    not null,
  cantidad_sistema numeric,
  cantidad_texto  text,
  precio          numeric,
  proveedor       text,
  fecha_estimada  date,
  es_punteo       boolean default false,
  activo          boolean default true,
  creado_en       timestamptz default now()
);

create table if not exists inventario_conteos (
  id             bigint generated always as identity primary key,
  item_id        bigint references inventario_items(id) on delete cascade,
  cantidad_fisica numeric,
  contado_por    text,
  sesion         text,
  nota           text,
  contado_en     timestamptz default now()
);

create index if not exists idx_items_area on inventario_items(area);
create index if not exists idx_items_tipo on inventario_items(tipo);
create index if not exists idx_conteos_item on inventario_conteos(item_id);

truncate inventario_items restart identity cascade;

insert into inventario_items (tipo,categoria,producto,talla,area,cantidad_sistema,cantidad_texto,precio,proveedor,es_punteo) values
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','2','Punto de venta',12,NULL,300,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','2','Bodega oficina',12,NULL,300,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','2','Produccion',8,NULL,300,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','4','Punto de venta',11,NULL,300,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','4','Bodega oficina',100,NULL,300,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','6','Punto de venta',0,NULL,300,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','6','Bodega oficina',18,NULL,300,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','6','Produccion',67,NULL,300,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','8','Punto de venta',10,NULL,300,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','8','Bodega oficina',71,NULL,300,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','10','Punto de venta',16,NULL,300,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','10','Bodega oficina',0,NULL,300,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','10','Produccion',30,NULL,300,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','12','Punto de venta',7,NULL,310,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','12','Bodega oficina',60,NULL,310,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','14','Punto de venta',3,NULL,310,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','14','Bodega oficina',60,NULL,310,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','16','Punto de venta',13,NULL,310,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','16','Bodega oficina',67,NULL,310,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','18','Punto de venta',7,NULL,300,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','18','Bodega oficina',24,NULL,300,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','XS','Punto de venta',0,NULL,NULL,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','S','Punto de venta',12,NULL,330,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','S','Bodega oficina',0,NULL,330,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','S','Produccion',8,NULL,330,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','M','Punto de venta',21,NULL,330,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','M','Bodega oficina',0,NULL,330,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','M','Produccion',9,NULL,330,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','L','Punto de venta',17,NULL,330,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','L','Bodega oficina',0,NULL,330,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','L','Produccion',8,NULL,330,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','XL','Punto de venta',16,NULL,365,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','XL','Bodega oficina',0,NULL,365,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','XL','Produccion',12,NULL,365,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','XXL','Punto de venta',15,NULL,365,NULL,false),
('uniforme','PLAYERA POLO BLANCA','PLAYERA POLO BLANCA','XXL','Bodega oficina',12,NULL,365,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','2','Punto de venta',18,NULL,270,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','2','Bodega oficina',0,NULL,270,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','2','Produccion',12,NULL,270,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','4','Punto de venta',13,NULL,270,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','4','Bodega oficina',0,NULL,270,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','4','Produccion',38,NULL,270,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','6','Punto de venta',13,NULL,270,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','6','Bodega oficina',0,NULL,270,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','6','Produccion',38,NULL,270,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','8','Punto de venta',12,NULL,270,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','8','Bodega oficina',0,NULL,270,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','8','Produccion',50,NULL,270,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','10','Punto de venta',8,NULL,270,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','10','Bodega oficina',0,NULL,270,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','10','Produccion',46,NULL,270,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','12','Punto de venta',0,NULL,270,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','12','Bodega oficina',0,NULL,270,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','12','Produccion',70,NULL,270,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','14','Punto de venta',0,NULL,270,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','14','Bodega oficina',0,NULL,270,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','14','Produccion',68,NULL,270,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','16','Punto de venta',4,NULL,270,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','16','Bodega oficina',0,NULL,270,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','16','Produccion',68,NULL,270,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','18','Punto de venta',0,NULL,280,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','18','Bodega oficina',0,NULL,280,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','18','Produccion',42,NULL,280,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','XS','Punto de venta',0,NULL,NULL,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','S','Punto de venta',6,NULL,280,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','S','Bodega oficina',0,NULL,280,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','S','Produccion',24,NULL,280,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','M','Punto de venta',7,NULL,280,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','M','Bodega oficina',0,NULL,280,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','M','Produccion',22,NULL,280,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','L','Punto de venta',7,NULL,280,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','L','Bodega oficina',0,NULL,280,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','L','Produccion',20,NULL,280,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','XL','Punto de venta',12,NULL,280,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','XL','Bodega oficina',0,NULL,280,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','XL','Produccion',6,NULL,280,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','XXL','Punto de venta',5,NULL,280,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','XXL','Bodega oficina',30,NULL,280,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','XXXL/46','Punto de venta',2,NULL,280,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','XXXL/46','Bodega oficina',0,NULL,280,NULL,false),
('uniforme','PLAYERA DEPORTIVA','PLAYERA DEPORTIVA','XXXL/46','Produccion',2,NULL,280,NULL,false),
('uniforme','FALDAS','FALDAS - MEZCLILLA PRIMARIA','6','Punto de venta',7,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - MEZCLILLA PRIMARIA','6','Bodega oficina',20,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - MEZCLILLA PRIMARIA','8','Punto de venta',4,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - MEZCLILLA PRIMARIA','8','Bodega oficina',22,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - MEZCLILLA PRIMARIA','10','Punto de venta',0,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - MEZCLILLA PRIMARIA','10','Bodega oficina',35,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - MEZCLILLA PRIMARIA','12','Punto de venta',0,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - MEZCLILLA PRIMARIA','12','Bodega oficina',21,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - MEZCLILLA PRIMARIA','14','Punto de venta',3,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - MEZCLILLA PRIMARIA','14','Bodega oficina',16,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - MEZCLILLA PRIMARIA','16','Punto de venta',14,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - MEZCLILLA PRIMARIA','16','Bodega oficina',0,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - MEZCLILLA PRIMARIA','18','Punto de venta',3,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - MEZCLILLA PRIMARIA','18','Bodega oficina',14,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - MEZCLILLA PRIMARIA','S','Punto de venta',15,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - MEZCLILLA PRIMARIA','S','Bodega oficina',0,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - MEZCLILLA PRIMARIA','M','Punto de venta',13,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - MEZCLILLA PRIMARIA','M','Bodega oficina',0,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - MEZCLILLA PRIMARIA','L','Punto de venta',8,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - MEZCLILLA PRIMARIA','L','Bodega oficina',0,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - MEZCLILLA PRIMARIA','XL','Punto de venta',0,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - MEZCLILLA PRIMARIA','XL','Bodega oficina',0,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - MEZCLILLA PRIMARIA','XXL','Punto de venta',0,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - MEZCLILLA PRIMARIA','XXL','Bodega oficina',0,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - ROJA KINDER','2','Punto de venta',0,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - ROJA KINDER','2','Bodega oficina',0,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - ROJA KINDER','2','Produccion',22,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - ROJA KINDER','4','Punto de venta',0,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - ROJA KINDER','4','Bodega oficina',0,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - ROJA KINDER','4','Produccion',22,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - ROJA KINDER','6','Punto de venta',4,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - ROJA KINDER','6','Bodega oficina',10,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - ROJA KINDER','6','Produccion',4,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - ROJA KINDER','8','Punto de venta',9,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - ROJA KINDER','8','Bodega oficina',14,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - ROJA KINDER','8','Produccion',2,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - ROJA KINDER','10','Punto de venta',10,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - ROJA KINDER','10','Bodega oficina',10,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - ROJA KINDER','12','Punto de venta',7,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - BLANCA KINDER','2','Punto de venta',2,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - BLANCA KINDER','2','Bodega oficina',0,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - BLANCA KINDER','2','Produccion',10,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - BLANCA KINDER','4','Punto de venta',1,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - BLANCA KINDER','4','Bodega oficina',0,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - BLANCA KINDER','4','Produccion',16,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - BLANCA KINDER','6','Punto de venta',6,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - BLANCA KINDER','6','Bodega oficina',5,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - BLANCA KINDER','6','Produccion',5,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - BLANCA KINDER','8','Punto de venta',17,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - BLANCA KINDER','8','Bodega oficina',0,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - BLANCA KINDER','10','Punto de venta',15,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - BLANCA KINDER','10','Bodega oficina',0,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - BLANCA KINDER','12','Punto de venta',4,NULL,325,NULL,false),
('uniforme','FALDAS','FALDAS - BLANCA KINDER','12','Bodega oficina',0,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','4','Punto de venta',0,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','4','Bodega oficina',0,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','4','Produccion',6,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','6','Punto de venta',16,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','6','Bodega oficina',6,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','6','Produccion',8,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','8','Punto de venta',10,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','8','Bodega oficina',6,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','8','Produccion',6,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','10','Punto de venta',9,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','10','Bodega oficina',6,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','10','Produccion',4,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','12','Punto de venta',1,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','12','Bodega oficina',19,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','12','Produccion',8,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','14','Punto de venta',3,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','14','Bodega oficina',17,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','14','Produccion',6,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','16','Punto de venta',5,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','16','Bodega oficina',18,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','18','Punto de venta',2,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','18','Bodega oficina',27,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','S','Punto de venta',6,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','S','Bodega oficina',5,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','M','Punto de venta',4,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','M','Bodega oficina',6,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','L','Punto de venta',11,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','L','Bodega oficina',12,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','XL','Punto de venta',0,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','XL','Bodega oficina',0,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','XXL','Punto de venta',0,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - AZUL PRIMARIA','XXL','Bodega oficina',0,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - ROJA KINDER','2','Punto de venta',18,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - ROJA KINDER','2','Bodega oficina',0,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - ROJA KINDER','2','Produccion',4,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - ROJA KINDER','4','Punto de venta',9,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - ROJA KINDER','4','Bodega oficina',0,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - ROJA KINDER','4','Produccion',15,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - ROJA KINDER','6','Punto de venta',8,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - ROJA KINDER','6','Bodega oficina',0,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - ROJA KINDER','6','Produccion',15,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - ROJA KINDER','8','Punto de venta',6,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - ROJA KINDER','8','Bodega oficina',0,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - ROJA KINDER','8','Produccion',8,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - ROJA KINDER','10','Punto de venta',6,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - ROJA KINDER','10','Bodega oficina',0,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - ROJA KINDER','12','Punto de venta',4,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - ROJA KINDER','12','Bodega oficina',9,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - BLANCA KINDER','2','Punto de venta',19,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - BLANCA KINDER','2','Bodega oficina',0,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - BLANCA KINDER','4','Punto de venta',2,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - BLANCA KINDER','4','Bodega oficina',0,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - BLANCA KINDER','4','Produccion',12,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - BLANCA KINDER','6','Punto de venta',21,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - BLANCA KINDER','6','Bodega oficina',0,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - BLANCA KINDER','6','Produccion',4,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - BLANCA KINDER','8','Punto de venta',2,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - BLANCA KINDER','8','Bodega oficina',9,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - BLANCA KINDER','8','Produccion',4,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - BLANCA KINDER','10','Punto de venta',4,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - BLANCA KINDER','10','Bodega oficina',3,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - BLANCA KINDER','12','Punto de venta',7,NULL,325,NULL,false),
('uniforme','BERMUDAS','BERMUDAS - BLANCA KINDER','12','Bodega oficina',11,NULL,325,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','0','Punto de venta',9,NULL,260,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','0','Bodega oficina',0,NULL,260,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','2','Punto de venta',3,NULL,260,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','2','Bodega oficina',18,NULL,260,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','4','Punto de venta',8,NULL,260,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','4','Bodega oficina',22,NULL,260,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','6','Punto de venta',8,NULL,260,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','6','Bodega oficina',20,NULL,260,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','8','Punto de venta',2,NULL,260,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','8','Bodega oficina',26,NULL,260,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','10','Punto de venta',9,NULL,260,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','10','Bodega oficina',14,NULL,260,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','12','Punto de venta',7,NULL,260,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','12','Bodega oficina',14,NULL,260,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','14','Punto de venta',5,NULL,260,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','14','Bodega oficina',16,NULL,260,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','16','Punto de venta',0,NULL,260,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','16','Bodega oficina',22,NULL,260,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','18','Punto de venta',5,NULL,260,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','18','Bodega oficina',14,NULL,260,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','S','Punto de venta',3,NULL,290,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','S','Bodega oficina',9,NULL,290,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','M','Punto de venta',6,NULL,290,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','M','Bodega oficina',10,NULL,290,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','L','Punto de venta',6,NULL,290,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','L','Bodega oficina',22,NULL,290,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','XL/42','Punto de venta',5,NULL,290,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','XL/42','Bodega oficina',9,NULL,290,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','XXL/44','Punto de venta',5,NULL,290,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','XXL/44','Bodega oficina',14,NULL,290,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','ESPECIAL XXXL','Punto de venta',0,NULL,290,NULL,false),
('uniforme','DEPORTES','DEPORTES - SHORT DEPORTIVO','ESPECIAL XXXL','Bodega oficina',2,NULL,290,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','2','Punto de venta',4,NULL,355,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','2','Bodega oficina',0,NULL,355,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','4','Punto de venta',7,NULL,355,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','4','Bodega oficina',8,NULL,355,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','6','Punto de venta',7,NULL,355,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','6','Bodega oficina',22,NULL,355,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','8','Punto de venta',2,NULL,355,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','8','Bodega oficina',8,NULL,355,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','10','Punto de venta',0,NULL,385,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','10','Bodega oficina',0,NULL,385,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','12','Punto de venta',0,NULL,385,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','12','Bodega oficina',0,NULL,385,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','14','Punto de venta',0,NULL,385,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','14','Bodega oficina',7,NULL,385,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','16','Punto de venta',1,NULL,385,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','16','Bodega oficina',0,NULL,385,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','S/36','Punto de venta',8,NULL,385,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','S/36','Bodega oficina',5,NULL,385,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','M','Punto de venta',6,NULL,385,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','M','Bodega oficina',10,NULL,385,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','L/40','Punto de venta',4,NULL,385,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','L/40','Bodega oficina',13,NULL,385,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','XL','Punto de venta',6,NULL,420,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','XL','Bodega oficina',2,NULL,420,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','XXL','Punto de venta',3,NULL,420,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','XXL','Bodega oficina',3,NULL,420,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','ESPECIAL XXXL','Punto de venta',0,NULL,420,NULL,false),
('uniforme','DEPORTES','DEPORTES - PANTS','ESPECIAL XXXL','Bodega oficina',1,NULL,420,NULL,false),
('uniforme','PLAYERA POLO PREPA DAMA','PLAYERA POLO PREPA DAMA - AZUL REY','S','Punto de venta',4,NULL,340,NULL,false),
('uniforme','PLAYERA POLO PREPA DAMA','PLAYERA POLO PREPA DAMA - AZUL REY','S','Bodega oficina',0,NULL,340,NULL,false),
('uniforme','PLAYERA POLO PREPA DAMA','PLAYERA POLO PREPA DAMA - AZUL REY','M','Punto de venta',9,NULL,340,NULL,false),
('uniforme','PLAYERA POLO PREPA DAMA','PLAYERA POLO PREPA DAMA - AZUL REY','M','Bodega oficina',0,NULL,340,NULL,false),
('uniforme','PLAYERA POLO PREPA DAMA','PLAYERA POLO PREPA DAMA - AZUL REY','L','Punto de venta',3,NULL,340,NULL,false),
('uniforme','PLAYERA POLO PREPA DAMA','PLAYERA POLO PREPA DAMA - AZUL REY','L','Bodega oficina',0,NULL,340,NULL,false),
('uniforme','PLAYERA POLO PREPA DAMA','PLAYERA POLO PREPA DAMA - AZUL REY','XL','Punto de venta',2,NULL,360,NULL,false),
('uniforme','PLAYERA POLO PREPA DAMA','PLAYERA POLO PREPA DAMA - AZUL REY','XL','Bodega oficina',0,NULL,360,NULL,false),
('uniforme','PLAYERA POLO PREPA DAMA','PLAYERA POLO PREPA DAMA - NEGRO','S','Punto de venta',4,NULL,340,NULL,false),
('uniforme','PLAYERA POLO PREPA DAMA','PLAYERA POLO PREPA DAMA - NEGRO','M','Punto de venta',5,NULL,340,NULL,false),
('uniforme','PLAYERA POLO PREPA DAMA','PLAYERA POLO PREPA DAMA - NEGRO','L','Punto de venta',3,NULL,340,NULL,false),
('uniforme','PLAYERA POLO PREPA DAMA','PLAYERA POLO PREPA DAMA - NEGRO','XL','Punto de venta',0,NULL,360,NULL,false),
('uniforme','PLAYARA POLO PREPA HOMBRE','PLAYARA POLO PREPA HOMBRE - AZUL REY','S','Punto de venta',3,NULL,340,NULL,false),
('uniforme','PLAYARA POLO PREPA HOMBRE','PLAYARA POLO PREPA HOMBRE - AZUL REY','S','Bodega oficina',0,NULL,340,NULL,false),
('uniforme','PLAYARA POLO PREPA HOMBRE','PLAYARA POLO PREPA HOMBRE - AZUL REY','M','Punto de venta',3,NULL,340,NULL,false),
('uniforme','PLAYARA POLO PREPA HOMBRE','PLAYARA POLO PREPA HOMBRE - AZUL REY','M','Bodega oficina',0,NULL,340,NULL,false),
('uniforme','PLAYARA POLO PREPA HOMBRE','PLAYARA POLO PREPA HOMBRE - AZUL REY','L','Punto de venta',1,NULL,340,NULL,false),
('uniforme','PLAYARA POLO PREPA HOMBRE','PLAYARA POLO PREPA HOMBRE - AZUL REY','L','Bodega oficina',0,NULL,340,NULL,false),
('uniforme','PLAYARA POLO PREPA HOMBRE','PLAYARA POLO PREPA HOMBRE - NEGRO','16','Punto de venta',3,NULL,340,NULL,false),
('uniforme','PLAYARA POLO PREPA HOMBRE','PLAYARA POLO PREPA HOMBRE - NEGRO','S','Punto de venta',6,NULL,340,NULL,false),
('uniforme','PLAYARA POLO PREPA HOMBRE','PLAYARA POLO PREPA HOMBRE - NEGRO','M','Punto de venta',9,NULL,340,NULL,false),
('uniforme','PLAYARA POLO PREPA HOMBRE','PLAYARA POLO PREPA HOMBRE - NEGRO','L','Punto de venta',6,NULL,340,NULL,false),
('uniforme','PLAYARA POLO PREPA HOMBRE','PLAYARA POLO PREPA HOMBRE - NEGRO','XL','Punto de venta',4,NULL,340,NULL,false),
('uniforme','HODDIE','HODDIE - HOODIE KINDER','2','Punto de venta',7,NULL,380,NULL,false),
('uniforme','HODDIE','HODDIE - HOODIE KINDER','2','Bodega oficina',4,NULL,380,NULL,false),
('uniforme','HODDIE','HODDIE - HOODIE KINDER','4','Punto de venta',0,NULL,380,NULL,false),
('uniforme','HODDIE','HODDIE - HOODIE KINDER','4','Bodega oficina',16,NULL,380,NULL,false),
('uniforme','HODDIE','HODDIE - HOODIE KINDER','6','Punto de venta',1,NULL,380,NULL,false),
('uniforme','HODDIE','HODDIE - HOODIE KINDER','6','Bodega oficina',24,NULL,380,NULL,false),
('uniforme','HODDIE','HODDIE - HOODIE KINDER','8','Punto de venta',14,NULL,380,NULL,false),
('uniforme','HODDIE','HODDIE - HOODIE KINDER','8','Bodega oficina',10,NULL,380,NULL,false),
('uniforme','HODDIE','HODDIE - HOODIE JUVENIL C/CAPUCHA PRIMARIA','XS','Punto de venta',8,NULL,380,NULL,false),
('uniforme','HODDIE','HODDIE - HOODIE JUVENIL C/CAPUCHA PRIMARIA','XS','Bodega oficina',15,NULL,380,NULL,false),
('uniforme','HODDIE','HODDIE - HOODIE JUVENIL C/CAPUCHA PRIMARIA','S','Punto de venta',7,NULL,380,NULL,false),
('uniforme','HODDIE','HODDIE - HOODIE JUVENIL C/CAPUCHA PRIMARIA','S','Bodega oficina',0,NULL,380,NULL,false),
('uniforme','HODDIE','HODDIE - HOODIE JUVENIL C/CAPUCHA PRIMARIA','M','Punto de venta',0,NULL,380,NULL,false),
('uniforme','HODDIE','HODDIE - HOODIE JUVENIL C/CAPUCHA PRIMARIA','M','Bodega oficina',0,NULL,380,NULL,false),
('uniforme','HODDIE','HODDIE - HOODIE JUVENIL C/CAPUCHA PRIMARIA','L','Punto de venta',0,NULL,380,NULL,false),
('uniforme','HODDIE','HODDIE - HOODIE JUVENIL C/CAPUCHA PRIMARIA','L','Bodega oficina',0,NULL,380,NULL,false),
('uniforme','HODDIE','HODDIE - HOODIE JUVENIL C/CAPUCHA PRIMARIA','XL','Punto de venta',0,NULL,380,NULL,false),
('uniforme','HODDIE','HODDIE - HOODIE JUVENIL C/CAPUCHA PRIMARIA','XL','Bodega oficina',5,NULL,380,NULL,false),
('uniforme','HODDIE','HODDIE - HOODIE ADULTO CAPUCHA SEC/PREPA','S','Punto de venta',8,NULL,430,NULL,false),
('uniforme','HODDIE','HODDIE - HOODIE ADULTO CAPUCHA SEC/PREPA','S','Bodega oficina',5,NULL,430,NULL,false),
('uniforme','HODDIE','HODDIE - HOODIE ADULTO CAPUCHA SEC/PREPA','M','Punto de venta',2,NULL,430,NULL,false),
('uniforme','HODDIE','HODDIE - HOODIE ADULTO CAPUCHA SEC/PREPA','M','Bodega oficina',0,NULL,430,NULL,false),
('uniforme','HODDIE','HODDIE - HOODIE ADULTO CAPUCHA SEC/PREPA','L','Punto de venta',10,NULL,430,NULL,false),
('uniforme','HODDIE','HODDIE - HOODIE ADULTO CAPUCHA SEC/PREPA','L','Bodega oficina',5,NULL,430,NULL,false),
('uniforme','HODDIE','HODDIE - HOODIE ADULTO CAPUCHA SEC/PREPA','XL','Punto de venta',2,NULL,430,NULL,false),
('uniforme','HODDIE','HODDIE - HOODIE ADULTO CAPUCHA SEC/PREPA','XL','Bodega oficina',0,NULL,430,NULL,false),
('uniforme','HODDIE','HODDIE - HOODIE ADULTO CAPUCHA SEC/PREPA','XXL','Punto de venta',3,NULL,430,NULL,false),
('uniforme','HODDIE','HODDIE - PLAYERAS EDECY','4','Bodega oficina',10,NULL,NULL,NULL,false),
('uniforme','HODDIE','HODDIE - PLAYERAS EDECY','6','Bodega oficina',27,NULL,NULL,NULL,false),
('uniforme','HODDIE','HODDIE - PLAYERAS EDECY','8','Bodega oficina',52,NULL,NULL,NULL,false),
('uniforme','HODDIE','HODDIE - PLAYERAS EDECY','10','Bodega oficina',75,NULL,NULL,NULL,false),
('uniforme','HODDIE','HODDIE - PLAYERAS EDECY','12','Bodega oficina',29,NULL,NULL,NULL,false),
('uniforme','HODDIE','HODDIE - PLAYERAS EDECY','14','Bodega oficina',14,NULL,NULL,NULL,false),
('uniforme','HODDIE','HODDIE - PLAYERAS EDECY','16','Bodega oficina',13,NULL,NULL,NULL,false),
('uniforme','HODDIE','HODDIE - PLAYERAS EDECY','S','Bodega oficina',83,NULL,NULL,NULL,false),
('uniforme','HODDIE','HODDIE - PLAYERAS EDECY','M','Bodega oficina',27,NULL,NULL,NULL,false),
('uniforme','HODDIE','HODDIE - PLAYERAS EDECY','G','Bodega oficina',6,NULL,NULL,NULL,false),
('uniforme','HODDIE','HODDIE - PLAYERAS EDECY','XL','Bodega oficina',10,NULL,NULL,NULL,false),
('uniforme','HODDIE','HODDIE - PLAYERAS EDECY','2XL','Bodega oficina',1,NULL,NULL,NULL,false),
('uniforme','HOODIE CUELLO REDONDO JUVENIL','HOODIE CUELLO REDONDO JUVENIL','XS','Bodega oficina',19,NULL,340,NULL,false),
('uniforme','HOODIE CUELLO REDONDO JUVENIL','HOODIE CUELLO REDONDO JUVENIL','S','Bodega oficina',3,NULL,340,NULL,false),
('uniforme','HOODIE CUELLO REDONDO JUVENIL','HOODIE CUELLO REDONDO JUVENIL','M','Bodega oficina',0,NULL,340,NULL,false),
('uniforme','HOODIE CUELLO REDONDO JUVENIL','HOODIE CUELLO REDONDO JUVENIL','L','Bodega oficina',6,NULL,340,NULL,false),
('uniforme','HOODIE CUELLO REDONDO JUVENIL','HOODIE CUELLO REDONDO JUVENIL','XL','Bodega oficina',3,NULL,340,NULL,false),
('uniforme','CONJUNTO DE INVIERNO','CONJUNTO DE INVIERNO','2','Punto de venta',1,NULL,700,NULL,false),
('uniforme','CONJUNTO DE INVIERNO','CONJUNTO DE INVIERNO','2','Bodega oficina',0,NULL,700,NULL,false),
('uniforme','CONJUNTO DE INVIERNO','CONJUNTO DE INVIERNO','4','Punto de venta',0,NULL,700,NULL,false),
('uniforme','CONJUNTO DE INVIERNO','CONJUNTO DE INVIERNO','4','Bodega oficina',0,NULL,700,NULL,false),
('uniforme','CONJUNTO DE INVIERNO','CONJUNTO DE INVIERNO','6','Punto de venta',4,NULL,700,NULL,false),
('uniforme','CONJUNTO DE INVIERNO','CONJUNTO DE INVIERNO','6','Bodega oficina',0,NULL,700,NULL,false),
('uniforme','CONJUNTO DE INVIERNO','CONJUNTO DE INVIERNO','8','Punto de venta',0,NULL,700,NULL,false),
('uniforme','CONJUNTO DE INVIERNO','CONJUNTO DE INVIERNO','8','Bodega oficina',0,NULL,700,NULL,false),
('uniforme','CHAMARRA ANTIGUA','CHAMARRA ANTIGUA','10','Bodega oficina',0,NULL,160,NULL,false),
('uniforme','CHAMARRA ANTIGUA','CHAMARRA ANTIGUA','16','Bodega oficina',0,NULL,160,NULL,false),
('uniforme','CHAMARRA ANTIGUA','CHAMARRA ANTIGUA','18','Bodega oficina',2,NULL,160,NULL,false),
('uniforme','CHAMARRA ANTIGUA','CHAMARRA ANTIGUA','S','Bodega oficina',10,NULL,160,NULL,false),
('uniforme','CHAMARRA ANTIGUA','CHAMARRA ANTIGUA','M/38','Bodega oficina',12,NULL,160,NULL,false),
('uniforme','CHAMARRA ANTIGUA','CHAMARRA ANTIGUA','L','Bodega oficina',1,NULL,NULL,NULL,false),
('recurso','LIBRETAS Y PAPELERIA','Cuadernos / Libretas','Cuadro grande','Punto de venta',254,NULL,NULL,NULL,false),
('recurso','LIBRETAS Y PAPELERIA','Cuadernos / Libretas','Cuadro grande','Bodega oficina',74,NULL,NULL,NULL,false),
('recurso','LIBRETAS Y PAPELERIA','Cuadernos / Libretas','Cuadro grande','Produccion',3,NULL,NULL,NULL,false),
('recurso','LIBRETAS Y PAPELERIA','Carpetas',NULL,'Bodega oficina',800,NULL,NULL,NULL,false),
('insumo','INSUMOS','cuellos niños',NULL,'Bodega',250,NULL,NULL,NULL,false),
('insumo','INSUMOS','cuellos adulto',NULL,'Bodega',338,NULL,NULL,NULL,false),
('insumo','INSUMOS','Puños',NULL,'Bodega',600,NULL,NULL,NULL,false),
('recurso','CUMPLEAÑOS','GLOBOS NEGROS GRANDES',NULL,'Bodega',6,NULL,NULL,NULL,false),
('recurso','UTILERIA','AROS HULA BRILLANTES',NULL,'Bodega',12,NULL,NULL,NULL,false),
('recurso','CUMPLEAÑOS','GLOBOS DE COLORES AZUL,ROSADA,ROJA',NULL,'Bodega',NULL,'rojos 3, negros 1, rosados 3, azul 3',NULL,NULL,false),
('recurso','CUMPLEAÑOS','cortina metalica azul',NULL,'Bodega',1,NULL,NULL,NULL,false),
('recurso','OBSEQUIOS PERSONAL CY','VASOS YETI PEQUEÑOS AZUL',NULL,'Bodega',2,NULL,NULL,NULL,false),
('recurso','ALCOHOL POSADA','LAMBRUSCO 1.5 TINTO',NULL,'Bodega',2,NULL,NULL,NULL,true),
('recurso','OBSEQUIOS PERSONAL CY','VASOS YETI PEQUEÑOS PLATEADOS',NULL,'Bodega',8,NULL,NULL,NULL,false),
('recurso','ALCOHOL POSADA','LAMBRUSO 1.5 ROSADO',NULL,'Bodega',2,NULL,NULL,NULL,true),
('recurso','OBSEQUIOS PERSONAL CY','cajas empack para guardar cosas',NULL,'Bodega',7,NULL,NULL,NULL,false),
('recurso','ALCOHOL POSADA','RON',NULL,'Bodega',0,'QUEDA UN POCO',NULL,NULL,true),
('recurso','ALCOHOL POSADA','JHON WALKER',NULL,'Bodega',0,'QUEDA UN POCO',NULL,NULL,true),
('recurso','ALCOHOL POSADA','JOSE CUERVO TEQUILA DE 990M L',NULL,'Bodega',1,NULL,NULL,NULL,true),
('recurso','ALCOHOL POSADA','VINO TINTO CAJAS',NULL,'Bodega',4,NULL,NULL,NULL,true),
('recurso','PAPELERIA','papel cascaron 1/8',NULL,'Bodega',7,NULL,NULL,NULL,false),
('recurso','Cuadernillos EN CAJA BLANCA TRANSPARENTE','matematicas vi antologia 3 grado prepa',NULL,'Bodega',2,NULL,NULL,NULL,false),
('recurso','PAPELERIA','hojas cafes',NULL,'Bodega',NULL,'40 aprox sueltas',NULL,NULL,false),
('recurso','Cuadernillos EN CAJA BLANCA TRANSPARENTE','geociencias 5 semestre',NULL,'Bodega',2,NULL,NULL,NULL,false),
('recurso','PAPELERIA','estambre rojo',NULL,'Bodega',1,NULL,NULL,NULL,false),
('recurso','Cuadernillos EN CAJA BLANCA TRANSPARENTE','diarios academicos prepa',NULL,'Bodega',5,NULL,NULL,NULL,false),
('recurso','PAPELERIA','palitos de bambu',NULL,'Bodega',NULL,'25 piezas',NULL,NULL,false),
('recurso','Cuadernillos EN CAJA BLANCA TRANSPARENTE','ciudadania activa',NULL,'Bodega',2,NULL,NULL,NULL,false),
('recurso','PAPELERIA','crayones traingulares jumbo 12 piezas',NULL,'Bodega',NULL,'9 paquetes',NULL,NULL,false),
('recurso','Cuadernillos EN CAJA BLANCA TRANSPARENTE','tutorias cuadernillo COLABORACION',NULL,'Bodega',6,NULL,NULL,NULL,false),
('recurso','PAPELERIA','palitos de madera pequeños de colores',NULL,'Bodega',78,NULL,NULL,NULL,false),
('recurso','Cuadernillos EN CAJA BLANCA TRANSPARENTE','tutorias cuadernillo AUTOREGULACION',NULL,'Bodega',3,NULL,NULL,NULL,false),
('recurso','PAPELERIA','palitos de madera grandes',NULL,'Bodega',13,NULL,NULL,NULL,false),
('recurso','Cuadernillos EN CAJA BLANCA TRANSPARENTE','tutorias cuadernillo PERSEVERANCIA',NULL,'Bodega',3,NULL,NULL,NULL,false),
('recurso','PAPELERIA','caja de gises de colores de 12 piezas',NULL,'Bodega',1,NULL,NULL,NULL,false),
('recurso','PAPELERIA','caja de gises de 10 piezas',NULL,'Bodega',1,NULL,NULL,NULL,false),
('recurso','PAPELERIA','borradores smarty candy de colores',NULL,'Bodega',7,NULL,NULL,NULL,false),
('recurso','PAPELERIA','borrador de migajon pelikan m40',NULL,'Bodega',19,NULL,NULL,NULL,false),
('recurso','PAPELERIA','corrector de pluma pelikan',NULL,'Bodega',4,NULL,NULL,NULL,false),
('recurso','PAPELERIA','marcatexto sharpie color amarillo',NULL,'Bodega',3,NULL,NULL,NULL,false),
('recurso','PAPELERIA','marcador de color base agua BACO rojo',NULL,'Bodega',1,NULL,NULL,NULL,false),
('recurso','PAPELERIA','marcador de color base agua BACO azul',NULL,'Bodega',1,NULL,NULL,NULL,false),
('recurso','PAPELERIA','plumon permanente punta gruesa signal negro',NULL,'Bodega',3,NULL,NULL,NULL,false),
('recurso','PAPELERIA','plumon permanente punta gruesa baco negro',NULL,'Bodega',2,NULL,NULL,NULL,false),
('recurso','PAPELERIA','plumon permanente punta fina signal negro',NULL,'Bodega',1,NULL,NULL,NULL,false),
('recurso','PAPELERIA','plumon sharpie metalico plateado',NULL,'Bodega',9,NULL,NULL,NULL,false),
('recurso','PAPELERIA','lapiz entrenador traingular smarty',NULL,'Bodega',9,NULL,NULL,NULL,false),
('recurso','PAPELERIA','lapiz entrenador traingular dixon',NULL,'Bodega',7,NULL,NULL,NULL,false),
('recurso','PAPELERIA','lapiz smarty pencil punta gruesa no 2',NULL,'Bodega',5,NULL,NULL,NULL,false),
('recurso','PAPELERIA','lapiz smarty pencil hexagonal no 2',NULL,'Bodega',4,NULL,NULL,NULL,false),
('recurso','PAPELERIA','lapiz mirado no 2 maped',NULL,'Bodega',83,NULL,NULL,NULL,false),
('recurso','PAPELERIA','Lapiz duo smarty triangular',NULL,'Bodega',9,NULL,NULL,NULL,false),
('recurso','PAPELERIA','pincel no 5',NULL,'Bodega',21,NULL,NULL,NULL,false),
('recurso','PAPELERIA','Brocha para pintar #3',NULL,'Bodega',1,NULL,NULL,NULL,false),
('recurso','PAPELERIA','Brocha para pintar #4',NULL,'Bodega',1,NULL,NULL,NULL,false),
('recurso','PAPELERIA','tijera smarty cortesitos usadas',NULL,'Bodega',2,NULL,NULL,NULL,false),
('recurso','PAPELERIA','pluma pint point 1.00 mm roja',NULL,'Bodega',4,NULL,NULL,NULL,false),
('recurso','PAPELERIA','pluma pint point 1.00 mm negra',NULL,'Bodega',1,NULL,NULL,NULL,false),
('recurso','PAPELERIA','puntillas .5 de grafito cajitas',NULL,'Bodega',5,NULL,NULL,NULL,false),
('recurso','PAPELERIA','lapiz rojo norma',NULL,'Bodega',4,NULL,NULL,NULL,false),
('recurso','PAPELERIA','lapiz rojo smarty',NULL,'Bodega',14,NULL,NULL,NULL,false),
('recurso','PAPELERIA','lapiz rojo papermate',NULL,'Bodega',2,NULL,NULL,NULL,false),
('recurso','PAPELERIA','cinta adhesiva circular de colores metalicas paquete',NULL,'Bodega',1,NULL,NULL,NULL,false),
('recurso','PAPELERIA','papel lustre rojo',NULL,'Bodega',13,NULL,NULL,NULL,false),
('recurso','PAPELERIA','libro para colorear de unicornios niña',NULL,'Bodega',1,NULL,NULL,NULL,false),
('recurso','PAPELERIA','cinta adhesiva canela',NULL,'Bodega',3,NULL,NULL,NULL,false),
('recurso','PAPELERIA','cinta adhesiva janel medida normal',NULL,'Bodega',4,NULL,NULL,NULL,false),
('recurso','PAPELERIA','cinta adhesiva janel doble',NULL,'Bodega',1,NULL,NULL,NULL,false),
('recurso','PAPELERIA','silico liquido de 250 ml nuevo',NULL,'Bodega',1,NULL,NULL,NULL,false),
('recurso','PAPELERIA','papel china verde paquetes de 3 piezas',NULL,'Bodega',6,NULL,NULL,NULL,false),
('recurso','PAPELERIA','silicon en barra gruesa',NULL,'Bodega',NULL,'40 piezas',NULL,NULL,false),
('recurso','PAPELERIA','silicon en barra delgada',NULL,'Bodega',47,NULL,NULL,NULL,false),
('recurso','PAPELERIA','pintura cafe vinilica BOMBIN 250 ml',NULL,'Bodega',1,NULL,NULL,NULL,false),
('recurso','PAPELERIA','pintura naranja vinilica BOMBIN 250 ml',NULL,'Bodega',2,NULL,NULL,NULL,false),
('recurso','PAPELERIA','plumon de pizarra verde MAGISTRAL',NULL,'Bodega',3,NULL,NULL,NULL,false),
('recurso','PAPELERIA','caja de grapas 5040 PILOT',NULL,'Bodega',3,NULL,NULL,NULL,false),
('recurso','PAPELERIA','pinzas de bambu chicas',NULL,'Bodega',NULL,'40 piezas',NULL,NULL,false),
('recurso','PAPELERIA','pompon no 50 morado',NULL,'Bodega',NULL,'10 piezas',NULL,NULL,false),
('recurso','PAPELERIA','pompon no 50 rosado',NULL,'Bodega',NULL,'10 piezas',NULL,NULL,false),
('recurso','PAPELERIA','pompon no 25 rojo',NULL,'Bodega',NULL,'25 piezas',NULL,NULL,false),
('recurso','PAPELERIA','plumas rojas de 5 gramos',NULL,'Bodega',NULL,'1 paquete',NULL,NULL,false),
('recurso','PAPELERIA','ojos movibles CONFETTI',NULL,'Bodega',NULL,'1 bolsa 50 piezas',NULL,NULL,false),
('recurso','PAPELERIA','collar metalico rojo no 6',NULL,'Bodega',NULL,'2 piezas',NULL,NULL,false),
('recurso','PAPELERIA','collar metalico rosado no 6',NULL,'Bodega',NULL,'2 piezas',NULL,NULL,false),
('recurso','PAPELERIA','Diamantina blanca 50 gramos',NULL,'Bodega',NULL,'5 bolsas',NULL,NULL,false),
('recurso','PAPELERIA','diamantina azul',NULL,'Bodega',NULL,'1 bolsa chica',NULL,NULL,false),
('recurso','PAPELERIA','diamantina dorada',NULL,'Bodega',NULL,'1 bolsa chica',NULL,NULL,false),
('recurso','PAPELERIA','Lentejuelas rosadas',NULL,'Bodega',NULL,'1 bolsa chica',NULL,NULL,false),
('recurso','PAPELERIA','Broche de presión no 2',NULL,'Bodega',NULL,'36 piezas',NULL,NULL,false),
('recurso','PAPELERIA','Hoja lluvia de estrellas metalico tornasol plateado',NULL,'Bodega',NULL,'4 piezas',NULL,NULL,false),
('recurso','PAPELERIA','Hoja lluvia de estrellas metalico tornasol azul',NULL,'Bodega',NULL,'9 piezas',NULL,NULL,false),
('recurso','PAPELERIA','papel lustre azul',NULL,'Bodega',NULL,'4 piezas',NULL,NULL,false),
('recurso','PAPELERIA','papel para envolver navidad posada',NULL,'Bodega',NULL,'4 piezas',NULL,NULL,false),
('recurso','PAPELERIA','resistiol 500ml',NULL,'Bodega',NULL,'21 botes',NULL,NULL,false),
('recurso','PAPELERIA','borrador verde pizarron',NULL,'Bodega',NULL,'12 piezas',NULL,NULL,false),
('recurso','PAPELERIA','sobres blancos',NULL,'Bodega',NULL,'34 piezas',NULL,NULL,false),
('recurso','PAPELERIA','sobres para cd de colores',NULL,'Bodega',NULL,'25 piezas',NULL,NULL,false),
('recurso','PAPELERIA','sobres manila',NULL,'Bodega',NULL,'41 piezas',NULL,NULL,false),
('recurso','PAPELERIA','Broches para archivo',NULL,'Bodega',NULL,'2 cajas',NULL,NULL,false),
('recurso','PAPELERIA','abatelenguas',NULL,'Bodega',NULL,'66 piezas',NULL,NULL,false),
('recurso','PAPELERIA','semicirculos',NULL,'Bodega',NULL,'12 piezas',NULL,NULL,false),
('recurso','PAPELERIA','escuadras',NULL,'Bodega',NULL,'10 piezas',NULL,NULL,false),
('recurso','PAPELERIA','compas',NULL,'Bodega',NULL,'5 piezas',NULL,NULL,false),
('recurso','PAPELERIA','juego de geometria maped',NULL,'Bodega',1,NULL,NULL,NULL,false),
('recurso','PAPELERIA','cordel gris',NULL,'Bodega',NULL,'1 pieza',NULL,NULL,false),
('recurso','PAPELERIA','Borrador smarty  art 25946 colores',NULL,'Bodega',NULL,'11 piezas',NULL,NULL,false),
('recurso','PAPELERIA','borrador pelikan M20',NULL,'Bodega',3,NULL,NULL,NULL,false),
('recurso','PAPELERIA','Borrador smarty candy color',NULL,'Bodega',NULL,'2 piezas',NULL,NULL,false),
('recurso','PAPELERIA','tajador de caja',NULL,'Bodega',2,NULL,NULL,NULL,false),
('recurso','PAPELERIA','tajador normal',NULL,'Bodega',1,NULL,NULL,NULL,false),
('recurso','PAPELERIA','sacapuntas metalico smarty art.25037',NULL,'Bodega',NULL,'2 piezas',NULL,NULL,false),
('recurso','Uniformes para empleados','28',NULL,'Bodega',1,NULL,NULL,NULL,false),
('recurso','Uniformes para empleados','32',NULL,'Bodega',1,NULL,NULL,NULL,false),
('recurso','Uniformes para empleados','32',NULL,'Bodega',1,NULL,NULL,NULL,false),
('recurso','Uniformes para empleados','grande',NULL,'Bodega',6,NULL,NULL,NULL,false),
('recurso','Uniformes para empleados','40',NULL,'Bodega',2,NULL,NULL,NULL,false),
('recurso','Uniformes para empleados','42',NULL,'Bodega',1,NULL,NULL,NULL,false),
('recurso','Uniformes para empleados','46',NULL,'Bodega',1,NULL,NULL,NULL,false),
('recurso','Faldas escolta','4',NULL,'Bodega',1,NULL,NULL,NULL,false),
('recurso','Faldas escolta','M',NULL,'Bodega',4,NULL,NULL,NULL,false),
('recurso','Faldas escolta','S',NULL,'Bodega',3,NULL,NULL,NULL,false),
('recurso','GORRAS','BLANCAS',NULL,'Bodega',4,NULL,NULL,NULL,false),
('recurso','GORRAS','AZUL',NULL,'Bodega',3,NULL,NULL,NULL,false),
('recurso','GORRAS','AZUL MARINA',NULL,'Bodega',1,NULL,NULL,NULL,false);